/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tugas3;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author X455LA
 */
public class FormKTP extends javax.swing.JFrame {

    private String nama;
    private String tempat;
    private String tanggal;
    private String alamat;
    private String rt;
    private Object Rw;
    private String kelurahan;
    private String kecamatan;
    private String kota;
    private String agama;
    private String status;
    private String goldar;
    private String pekerjaan;

    /**
     * Creates new form FormKTP
     */
    public FormKTP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGSex = new javax.swing.ButtonGroup();
        BGKewarganegaraan = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TFNama = new javax.swing.JTextField();
        TFTempat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TFTanggal = new javax.swing.JTextField();
        RBLaki = new javax.swing.JRadioButton();
        RBPerempuan = new javax.swing.JRadioButton();
        TFAlamat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TFRt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TFRW = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TFKelurahan = new javax.swing.JTextField();
        TFKecamatan = new javax.swing.JTextField();
        TFKota = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        CBAgama = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        CBStatus = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        CBGoldar = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        TFPekerjaan = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        RBWna = new javax.swing.JRadioButton();
        RBWni = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        BChose = new javax.swing.JButton();
        Lfoto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Breset = new javax.swing.JButton();
        BRegister = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FORM ISIAN\n", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(153, 0, 0))); // NOI18N

        jLabel3.setText("Nama");

        jLabel4.setText("Tempat/Tanggal Lahir");

        jLabel5.setText("Jenis Kelamin");

        jLabel6.setText("Alamat");

        TFTempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFTempatActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("/");

        BGSex.add(RBLaki);
        RBLaki.setText("Laki - laki");

        BGSex.add(RBPerempuan);
        RBPerempuan.setText("Perempuan");

        TFAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFAlamatActionPerformed(evt);
            }
        });

        jLabel8.setText("RT/RW");

        TFRt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFRtActionPerformed(evt);
            }
        });

        jLabel9.setText("/");

        jLabel10.setText("Kel/Desa");

        jLabel11.setText("Kecamatan");

        jLabel12.setText("Kota");

        TFKecamatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFKecamatanActionPerformed(evt);
            }
        });

        jLabel13.setText("Agama");

        CBAgama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ISLAM", "PROTESTAN", "KRISTEN", "HINDU", "BUDHA" }));

        jLabel14.setText("Status");

        CBStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KAWIN", "BELUM KAWIN" }));

        jLabel15.setText("Golongan Darah");

        CBGoldar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "AB", "O" }));
        CBGoldar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBGoldarActionPerformed(evt);
            }
        });

        jLabel16.setText("Pekerjaan");

        TFPekerjaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFPekerjaanActionPerformed(evt);
            }
        });

        jLabel17.setText("Kewarganegaraan");

        BGKewarganegaraan.add(RBWna);
        RBWna.setText("WNA");

        BGKewarganegaraan.add(RBWni);
        RBWni.setText("WNI");
        RBWni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBWniActionPerformed(evt);
            }
        });

        jLabel2.setText("Pilih fotomu 3 x 4");

        BChose.setText("Chose");
        BChose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BChoseActionPerformed(evt);
            }
        });

        Lfoto.setBackground(new java.awt.Color(255, 255, 255));
        Lfoto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Picture", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(0, 51, 51))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)))
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBGoldar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TFAlamat)
                                .addComponent(TFPekerjaan)
                                .addComponent(TFKota)
                                .addComponent(TFKecamatan)
                                .addComponent(TFKelurahan)
                                .addComponent(TFRW)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(TFTempat, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TFTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(RBLaki)
                                            .addGap(18, 18, 18)
                                            .addComponent(RBPerempuan))
                                        .addComponent(CBAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CBStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(RBWna)
                                            .addGap(18, 18, 18)
                                            .addComponent(RBWni))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(TFRt, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel9))
                                        .addComponent(TFNama))
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addComponent(BChose)
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Lfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TFNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TFTempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(TFTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(RBLaki)
                            .addComponent(RBPerempuan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TFAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(TFRt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(TFRW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(TFKelurahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(TFKecamatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(CBAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBGoldar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(TFPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(RBWna)
                            .addComponent(RBWni)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BChose)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("FORM KARTU TANDA PENDUDUK");

        Breset.setText("RESET");
        Breset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BresetActionPerformed(evt);
            }
        });

        BRegister.setText("REGISTER");
        BRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BRegisterMouseClicked(evt);
            }
        });
        BRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRegisterActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(96, 96, 96)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Breset)
                        .addGap(18, 18, 18)
                        .addComponent(BRegister))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Breset)
                    .addComponent(BRegister))
                .addGap(60, 60, 60))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TFAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFAlamatActionPerformed

    private void TFTempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFTempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFTempatActionPerformed

    private void TFRtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFRtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFRtActionPerformed

    private void TFKecamatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFKecamatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFKecamatanActionPerformed

    private void CBGoldarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBGoldarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBGoldarActionPerformed

    private void TFPekerjaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFPekerjaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFPekerjaanActionPerformed

    private void RBWniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBWniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBWniActionPerformed

    private void BresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BresetActionPerformed
        // TODO add your handling code here:
        TFNama.setText("");
        TFTempat.setText("");
        TFTanggal.setText("");
        BGSex.clearSelection();
        TFAlamat.setText("");
        TFRt.setText("");
        TFRW.setText("");
        TFKelurahan.setText("");
        TFKota.setText("");
        TFPekerjaan.setText("");
        CBAgama.setSelectedIndex(0);
        CBStatus.setSelectedIndex(0);
        CBGoldar.setSelectedIndex(0);
        BGKewarganegaraan.clearSelection();
        
        
        
    }//GEN-LAST:event_BresetActionPerformed
String gambar;
File filegambar = null;
    private void BRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRegisterActionPerformed
        outKTP output = new outKTP();  
        
        //output.tfNama1.setText(this.tfNama.getText());
        outKTP.TONama.setText(this.TFNama.getText());
        outKTP.TOTempat.setText(this.TFTempat.getText());
        outKTP.TOTanggal.setText(this.TFTanggal.getText());
        //outKTP.TOJeniskelamin.setText(this.TFJenisKelamin.getText());
        if (RBLaki.isSelected()) {
            outKTP.TOJeniskelamin.setText(this.RBLaki.getText());
        }
        else if (RBPerempuan.isSelected()) {
            
           outKTP.TOJeniskelamin.setText(this.RBPerempuan.getText());
        }
        outKTP.TOAlamat.setText(this.TFAlamat.getText());
        outKTP.TORT.setText(this.TFRt.getText());
        outKTP.TORW.setText(this.TFRW.getText());
        outKTP.TODesa.setText(this.TFKelurahan.getText());
        outKTP.TOKota.setText(this.TFKota.getText());
        outKTP.TOPekerjaan.setText(this.TFPekerjaan.getText());
        outKTP.TOAgama.setText(this.CBAgama.getSelectedItem().toString());
        outKTP.TOStatus.setText(this.CBStatus.getSelectedItem().toString());
        outKTP.TOGoldar.setText(this.CBGoldar.getSelectedItem().toString());
        
        if (RBWna.isSelected()) {
            outKTP.TOKewarganegaraan.setText(this.RBWna.getText());
        }  
        else if (RBWni.isSelected()) {
            
            outKTP.TOKewarganegaraan.setText(this.RBWni.getText());
        }
        outKTP.Lfoto.setIcon(this.Lfoto.getIcon());
        output.setVisible(true);
    }//GEN-LAST:event_BRegisterActionPerformed

    
    
    private void BChoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BChoseActionPerformed
         JFileChooser foto =new JFileChooser();
        int returnVal = foto.showOpenDialog(null);
        
        
        if(returnVal ==JFileChooser.APPROVE_OPTION){
            filegambar = foto.getSelectedFile();
            String filename = filegambar.getAbsolutePath();
        }
        try {
        BufferedImage gambar=ImageIO.read(filegambar);
        ImageIcon icon=new ImageIcon(gambar.getScaledInstance(150,200,10));
        Lfoto.setIcon(icon);//buat nampilkan pas chose
   
       // outKTP.Lfoto.setIcon(icon);// buat nampilkan pas register
        
        //JFrame2 tampil = new JFrame();
        //Lfoto.setVisible(true);
        }
        catch(IOException e) {e.getMessage();}   
    }//GEN-LAST:event_BChoseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BRegisterMouseClicked
        // TODO add your handling code here:
        //.setVisible(true);
    }//GEN-LAST:event_BRegisterMouseClicked
/*
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(outKTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(outKTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(outKTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(outKTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKTP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BChose;
    private javax.swing.ButtonGroup BGKewarganegaraan;
    private javax.swing.ButtonGroup BGSex;
    private javax.swing.JButton BRegister;
    private javax.swing.JButton Breset;
    private javax.swing.JComboBox<String> CBAgama;
    private javax.swing.JComboBox<String> CBGoldar;
    private javax.swing.JComboBox<String> CBStatus;
    private javax.swing.JLabel Lfoto;
    private javax.swing.JRadioButton RBLaki;
    private javax.swing.JRadioButton RBPerempuan;
    private javax.swing.JRadioButton RBWna;
    private javax.swing.JRadioButton RBWni;
    private javax.swing.JTextField TFAlamat;
    private javax.swing.JTextField TFKecamatan;
    private javax.swing.JTextField TFKelurahan;
    private javax.swing.JTextField TFKota;
    private javax.swing.JTextField TFNama;
    private javax.swing.JTextField TFPekerjaan;
    private javax.swing.JTextField TFRW;
    private javax.swing.JTextField TFRt;
    private javax.swing.JTextField TFTanggal;
    private javax.swing.JTextField TFTempat;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
