package Tugas4;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author X455LA
 */
public class LatihanBorderLayout extends javax.swing.JFrame {

    /**
     * Creates new form LatihanBorderLayout
     */
    public LatihanBorderLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PHead = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        BtnHome = new javax.swing.JButton();
        BtnProfile = new javax.swing.JButton();
        BtnGaleri = new javax.swing.JButton();
        BtnInformasi = new javax.swing.JButton();
        BtnAbout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        PFooter = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PRight = new javax.swing.JPanel();
        PLeft = new javax.swing.JPanel();
        PKonten = new javax.swing.JPanel();
        PHome = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        PProfile = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        PGaleri = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        PInformasi = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        PAbout = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENUUTAMABorderLayout");

        PHead.setBackground(new java.awt.Color(153, 0, 0));

        jToolBar1.setRollover(true);

        BtnHome.setText("HOME");
        BtnHome.setFocusable(false);
        BtnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnHomeMouseClicked(evt);
            }
        });
        jToolBar1.add(BtnHome);

        BtnProfile.setText("Profile");
        BtnProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnProfileMouseClicked(evt);
            }
        });
        jToolBar1.add(BtnProfile);

        BtnGaleri.setText("Galeri");
        BtnGaleri.setFocusable(false);
        BtnGaleri.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnGaleri.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnGaleri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnGaleriMouseClicked(evt);
            }
        });
        jToolBar1.add(BtnGaleri);

        BtnInformasi.setText("Informasi");
        BtnInformasi.setFocusable(false);
        BtnInformasi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnInformasi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnInformasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnInformasiMouseClicked(evt);
            }
        });
        jToolBar1.add(BtnInformasi);

        BtnAbout.setText("About");
        BtnAbout.setFocusable(false);
        BtnAbout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnAbout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAboutMouseClicked(evt);
            }
        });
        BtnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAboutActionPerformed(evt);
            }
        });
        jToolBar1.add(BtnAbout);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SISTEM INFORMASI AKADEMIK");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PROGRAM STUDI TEKNIK INFORMATIKA");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("UP. FKTI UNMUL");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/UNMUL.jpg"))); // NOI18N

        javax.swing.GroupLayout PHeadLayout = new javax.swing.GroupLayout(PHead);
        PHead.setLayout(PHeadLayout);
        PHeadLayout.setHorizontalGroup(
            PHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PHeadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PHeadLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(294, Short.MAX_VALUE))
        );
        PHeadLayout.setVerticalGroup(
            PHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PHeadLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PHeadLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(PHead, java.awt.BorderLayout.PAGE_START);

        PFooter.setBackground(new java.awt.Color(153, 0, 0));

        jLabel4.setText("PRAKTIKUM PEMROGRAMAN VISUAL");

        jLabel5.setText("Copyright@2017");

        javax.swing.GroupLayout PFooterLayout = new javax.swing.GroupLayout(PFooter);
        PFooter.setLayout(PFooterLayout);
        PFooterLayout.setHorizontalGroup(
            PFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PFooterLayout.createSequentialGroup()
                .addGroup(PFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PFooterLayout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jLabel4))
                    .addGroup(PFooterLayout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(jLabel5)))
                .addContainerGap(307, Short.MAX_VALUE))
        );
        PFooterLayout.setVerticalGroup(
            PFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PFooterLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(PFooter, java.awt.BorderLayout.PAGE_END);

        PRight.setBackground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout PRightLayout = new javax.swing.GroupLayout(PRight);
        PRight.setLayout(PRightLayout);
        PRightLayout.setHorizontalGroup(
            PRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        PRightLayout.setVerticalGroup(
            PRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        getContentPane().add(PRight, java.awt.BorderLayout.LINE_END);

        PLeft.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout PLeftLayout = new javax.swing.GroupLayout(PLeft);
        PLeft.setLayout(PLeftLayout);
        PLeftLayout.setHorizontalGroup(
            PLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        PLeftLayout.setVerticalGroup(
            PLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        getContentPane().add(PLeft, java.awt.BorderLayout.LINE_START);

        PKonten.setBackground(new java.awt.Color(255, 204, 102));
        PKonten.setLayout(new java.awt.CardLayout());

        PHome.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/wisuda.png"))); // NOI18N

        javax.swing.GroupLayout PHomeLayout = new javax.swing.GroupLayout(PHome);
        PHome.setLayout(PHomeLayout);
        PHomeLayout.setHorizontalGroup(
            PHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PHomeLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(48, 48, 48))
        );
        PHomeLayout.setVerticalGroup(
            PHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PHomeLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        PKonten.add(PHome, "card6");

        jLabel6.setText("myprofile");

        javax.swing.GroupLayout PProfileLayout = new javax.swing.GroupLayout(PProfile);
        PProfile.setLayout(PProfileLayout);
        PProfileLayout.setHorizontalGroup(
            PProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PProfileLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel6)
                .addContainerGap(508, Short.MAX_VALUE))
        );
        PProfileLayout.setVerticalGroup(
            PProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PProfileLayout.createSequentialGroup()
                .addContainerGap(311, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(51, 51, 51))
        );

        PKonten.add(PProfile, "card2");

        PGaleri.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("galeri");

        javax.swing.GroupLayout PGaleriLayout = new javax.swing.GroupLayout(PGaleri);
        PGaleri.setLayout(PGaleriLayout);
        PGaleriLayout.setHorizontalGroup(
            PGaleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PGaleriLayout.createSequentialGroup()
                .addContainerGap(545, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(28, 28, 28))
        );
        PGaleriLayout.setVerticalGroup(
            PGaleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PGaleriLayout.createSequentialGroup()
                .addContainerGap(327, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(35, 35, 35))
        );

        PKonten.add(PGaleri, "card3");

        PInformasi.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setText("Inforamasi");

        javax.swing.GroupLayout PInformasiLayout = new javax.swing.GroupLayout(PInformasi);
        PInformasi.setLayout(PInformasiLayout);
        PInformasiLayout.setHorizontalGroup(
            PInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PInformasiLayout.createSequentialGroup()
                .addContainerGap(519, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(30, 30, 30))
        );
        PInformasiLayout.setVerticalGroup(
            PInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PInformasiLayout.createSequentialGroup()
                .addContainerGap(320, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(42, 42, 42))
        );

        PKonten.add(PInformasi, "card4");

        PAbout.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("About");

        javax.swing.GroupLayout PAboutLayout = new javax.swing.GroupLayout(PAbout);
        PAbout.setLayout(PAboutLayout);
        PAboutLayout.setHorizontalGroup(
            PAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAboutLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel9)
                .addContainerGap(538, Short.MAX_VALUE))
        );
        PAboutLayout.setVerticalGroup(
            PAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAboutLayout.createSequentialGroup()
                .addContainerGap(321, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(41, 41, 41))
        );

        PKonten.add(PAbout, "card5");

        getContentPane().add(PKonten, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Data");

        jMenu4.setText("Input Data");
        jMenu1.add(jMenu4);

        jMenuItem1.setText("Cari Data");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Data Yudisium");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Keluar");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAboutActionPerformed

    private void BtnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnHomeMouseClicked
        // TODO add your handling code here:
        PHome.setVisible(true);
        PProfile.setVisible(false);
        PGaleri.setVisible(false);
        PInformasi.setVisible(false);
        PAbout.setVisible(false);
        
    }//GEN-LAST:event_BtnHomeMouseClicked

    private void BtnProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnProfileMouseClicked
        // TODO add your handling code here:
        PProfile.setVisible(true);
        PHome.setVisible(false);
        PGaleri.setVisible(false);
        PInformasi.setVisible(false);
        PAbout.setVisible(false);
    }//GEN-LAST:event_BtnProfileMouseClicked

    private void BtnGaleriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnGaleriMouseClicked
        // TODO add your handling code here:
        PGaleri.setVisible(true);
        PProfile.setVisible(false);
        PHome.setVisible(false);
        PInformasi.setVisible(false);
        PAbout.setVisible(false);
    }//GEN-LAST:event_BtnGaleriMouseClicked

    private void BtnInformasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnInformasiMouseClicked
        // TODO add your handling code here:
       PInformasi.setVisible(true);
        PGaleri.setVisible(false);
        PProfile.setVisible(false);
        PHome.setVisible(false);
        PAbout.setVisible(false);
    }//GEN-LAST:event_BtnInformasiMouseClicked

    private void BtnAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAboutMouseClicked
        // TODO add your handling code here:
        PAbout.setVisible(true);
         PInformasi.setVisible(false);
        PGaleri.setVisible(false);
        PProfile.setVisible(false);
        PHome.setVisible(false);
        
    }//GEN-LAST:event_BtnAboutMouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LatihanBorderLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LatihanBorderLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LatihanBorderLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LatihanBorderLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LatihanBorderLayout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAbout;
    private javax.swing.JButton BtnGaleri;
    private javax.swing.JButton BtnHome;
    private javax.swing.JButton BtnInformasi;
    private javax.swing.JButton BtnProfile;
    private javax.swing.JPanel PAbout;
    private javax.swing.JPanel PFooter;
    private javax.swing.JPanel PGaleri;
    private javax.swing.JPanel PHead;
    private javax.swing.JPanel PHome;
    private javax.swing.JPanel PInformasi;
    private javax.swing.JPanel PKonten;
    private javax.swing.JPanel PLeft;
    private javax.swing.JPanel PProfile;
    private javax.swing.JPanel PRight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
